### ISSUE TITLE
Dúvida sobre implementação de Algoritmo usado na aula sobre listas

### ISSUE THREAD

**Issue by raulpy271** [valdigleis/Curso_APP#1]
Olá Professor, uma dúvida sobre a aula de hoje (aula 04).

A gente implementou um functor que verifica se listas são iguais da seguinte forma:

```pl
igualdade( [Item | V], [Item | V] ).                         %% caso base
igualdade( [Item | L1], [Item | L2] ) :- igualdade(L1, L2).  %% caso recursivo 
```

No entanto, o caso recursivo só seria executado quando as listas fosse diferentes. Pois sempre que elas forem iguais o caso base será executado, e assim finalizando a busca. 

Portanto, quando as listas são iguais o caso recursivo é inutil. Logo, para a implementação do algoritmo, não é necessário recursão, somente o caso base. Dessa forma:

```pl
igualdade( [Item | V], [Item | V] ). 
```

Ou de forma mais simples:

```pl
igualdade(Lista, Lista). 
```

Eu tenho razão?

**Comment by valdigleis** [comment]
Eita Raul tem razão realmente! Então fica como desafio para você, implementar o teste de igualdade que faz a chamada recursiva em ambos os casos! rsrsrs

**Comment by raulpy271** [comment]
Entedido! No caso base imaginamos que a variável `V` seria o vazio. então simplismente podemos substitui-la pelo vazio para funcionar corretamente:

```pl
igualdade( [Item | [] ], [Item | [] ] ).                     %% caso base
igualdade( [Item | L1], [Item | L2] ) :- igualdade(L1, L2).  %% caso recursivo 
```

Agora sim?

**Comment by valdigleis** [comment]
Isso!

**Comment by valdigleis** [comment]
> Isso!
